# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=63, unique=True)),
                ('banned_on', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'fly_banned_domains',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('banned_on', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'fly_banned_ips',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, max_length=63, unique=True)),
                ('banned_on', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'fly_banned_words',
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fly_image_uploads',
                'ordering': ('upload_date',),
            },
        ),
    ]
