# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160129_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubmission',
            name='a',
            field=models.BooleanField(default=False),
        ),
    ]
