# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_questionsubmission_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='me',
            old_name='level',
            new_name='current_xp',
        ),
        migrations.RemoveField(
            model_name='me',
            name='xp',
        ),
        migrations.AddField(
            model_name='me',
            name='xplevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.XPLevel'),
            preserve_default=False,
        ),
    ]
