# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160129_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=63, null=True)),
                ('description', models.CharField(blank=True, max_length=511, null=True)),
            ],
            options={
                'managed': True,
                'db_tablespace': '',
                'verbose_name': 'badge Translation',
                'default_permissions': (),
                'db_table': 'fly_badges_translation',
            },
        ),
        migrations.RemoveField(
            model_name='badge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='title',
        ),
        migrations.AddField(
            model_name='badgetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.Badge'),
        ),
        migrations.AlterUniqueTogether(
            name='badgetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
