# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160130_0247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badgetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='badgetranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.DeleteModel(
            name='BadgeTranslation',
        ),
    ]
