# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160130_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='description_en',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_es',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_fr',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_en',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_es',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='title_fr',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
