# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160130_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xplevel',
            name='required_xp',
        ),
        migrations.AddField(
            model_name='xplevel',
            name='max_xp',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='xplevel',
            name='min_xp',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 Minutes'), (30, '30 Minutes'), (60, '1 Hour')], default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='xplevel',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 Minutes'), (30, '30 Minutes'), (60, '1 Hour')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
