# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160130_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='me',
            old_name='current_xp',
            new_name='xp',
        ),
        migrations.AddField(
            model_name='me',
            name='xp_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
