# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 17:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160131_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='times',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
