# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 17:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160131_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='earned_xp',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
