# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160131_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
