# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_creditgoal_finalgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgoal',
            name='for_other_want',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
    ]
