# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160201_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgoal',
            name='for_other_want',
            field=models.CharField(blank=True, default='', max_length=63, null=True),
        ),
    ]
