# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 16:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20160201_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Badge'), (2, 'Goal Badge'), (3, 'Education Badge'), (4, 'Resource Badge')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='creditgoal',
            name='points',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(850)]),
        ),
    ]
