# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20160202_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
