# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
