# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20160202_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_prerequisites',
            field=models.BooleanField(default=False),
        ),
    ]
