# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_quizsubmission_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubmission',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
            preserve_default=False,
        ),
    ]
