# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_questionsubmission_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsubmission',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Quiz'),
        ),
    ]
