# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20160204_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='description_en',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='description_es',
            new_name='text_es',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='description_fr',
            new_name='text_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_fr',
        ),
    ]
