# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20160204_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='false_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='false_choice_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='false_choice_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='false_choice_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='true_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='true_choice_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='true_choice_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='true_choice_fr',
        ),
    ]
