# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20160204_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsubmission',
            name='tf_answer',
        ),
    ]
