# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_questionsubmission_tf_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='marks',
            new_name='final_mark',
        ),
        migrations.RenameField(
            model_name='questionsubmission',
            old_name='marks',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='marks',
            new_name='final_mark',
        ),
    ]
