# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20160205_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='xplevel',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
