# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20160206_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='wants_course_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='me',
            name='wants_goal_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='me',
            name='wants_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='me',
            name='wants_resource_notify',
            field=models.BooleanField(default=False),
        ),
    ]
