# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 21:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20160206_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=127)),
                ('url', models.URLField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Social Media'), (2, 'Blogs'), (3, 'Other Cool Apps')], db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'db_table': 'fly_resource_links',
            },
        ),
    ]
