# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_resourcelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='title_en',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='resourcelink',
            name='title_es',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='resourcelink',
            name='title_fr',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
