# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20160206_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
        migrations.AddField(
            model_name='badge',
            name='colour',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
