# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20160207_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xplevel',
            old_name='level',
            new_name='num',
        ),
    ]
