# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 21:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0040_auto_20160209_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Level Up Notifiction'), (2, 'New Badge Notification'), (3, 'Custom Notification')], db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('title', models.CharField(blank=True, max_length=511, null=True)),
                ('text', models.CharField(blank=True, max_length=511, null=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xplevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.XPLevel')),
            ],
            options={
                'db_table': 'fly_notifications',
            },
        ),
        migrations.AlterField(
            model_name='creditgoal',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='finalgoal',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='me',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='fly_user_badges', to='api.Badge'),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
