# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20160209_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 9, 21, 51, 59, 81011, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
